### ISSUE TITLE
Internal Transport queue to limit backpressure

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-ruby#1130]
We should have an internal transport queue that at one point stops accepting events
e.g. on JS we have a queue that in max can hold 30 events in queue that should be sent to Sentry.
If the queue is full because we are sending so much the transport is not accepting anything anymore.

Python
https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/transport.py#L130

**Comment by st0012** [comment]
Adding a job queue isn't an issue at all. But if we want to make the event processing non-blocking, that'll make things a bit trickier. Here are some contexts:

- Many Ruby users have already used their own background workers + `config.async` to send their events asynchronously.
- The current backgrounding pattern is to enqueue/create a thread for each event. Not having a long-living background worker dedicated on consuming events. For example:

```ruby
config.async = lambda { |event|
  Thread.new { Sentry.send_event(event) }
}

# or

config.async = lambda { |event| SentryJob.perform_later(event) }

class SentryJob < ActiveJob::Base
  queue_as :default

  def perform(event)
    Sentry.send_event(event)
  end
end
```

- If I understand it correctly, `sentry-python`'s worker is embedded at the `Transport` level and it spawns a thread dedicated at consuming the events passed to the transport (`HttpTransport` in particular).

And here are my thoughts:

- We need to choose between having a dedicated background thread consuming events (like `sentry-python`) and asynchronously sending individual events (the current `async` option). If we want to introduce a dedicated background worker thread, we have to remove the `async` option, because it'd be terrible to debug if we support both.
- We should use make an exception on our "no dependency rule" and use [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby) for the implementation. It's basically a standard library in the Ruby community when dealing with concurrent/async related tasks. It's also used by Rails in multiple places ([example](https://github.com/rails/rails/blob/7ee31150eb590136ace3458d3a0ca29364f4b1b4/activejob/lib/active_job/queue_adapters/async_adapter.rb#L4-L6)).

**Comment by HazAT** [comment]
So if Ruby devs are used to having their own "async background worker" they are responsible for managing the queue size.
Our transport by default should be having one. So if we do `Thread.new { Sentry.send_event(event) }` he need to check out internal synchronized queue to make sure we are able to handle the event.

**Comment by st0012** [comment]
ok, so here's what I'll do:

1. implement an event queue + a background worker for non-blocking `send_event` (use [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby) as a dependency)
2. remove `config.async`, so this won't be managed by users anymore

sounds good?

**Comment by st0012** [comment]
To summarize our conclusions:

1. Introduce a built-in background worker to send events in a non-blocking way.
2. The background worker will only be activated if the user doesn't config the `async` option. So users can still choose their preferred approaches to send events asynchronously.
3. The built-in background worker will consume events from a queue, which has a limit of 30 events. If the number of events exceeds the queue limit, new events will be dropped.
4. The background worker will be built on top of [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby). This is because:
  - It is already a Rails' dependency. So most of our users should already have it installed.
  - The cost of maintaining our own thread pool for the worker is just too high. Not to mention we need to do it in a way that's compatible in both JRuby and CRuby.
