### ISSUE TITLE
Extras leak from one example to another

### ISSUE THREAD

**Issue by get-dmitry** [getsentry/sentry-ruby#1300]
**Describe the bug**

According to sentry-ruby migration guide, this is the way to Set Contextual Data (local):

`Sentry.set_extras(debug: true)`

Performing this, however, leads to setting extra in global contextual data,
which is not cleared between running examples in RSpec.

**To Reproduce**

```
class TestSetExtras
  def set_sentry_context(response)
    Sentry.set_extras(response_payload: response)
  end
end

class TestCleanExtras
  def report_exception
    raise ArgumentError.new
  rescue ArgumentError => e
    Sentry.capture_exception(e)
  end
end

RSpec.describe TestSetExtras do
  let(:response) { double('Response') }
  subject { described_class.new.set_sentry_context(response) }
  it { subject }
end

RSpec.describe TestCleanExtras do
  subject { described_class.new.report_exception }
  it 'Should be blank but its not' do
    subject
    expect(Sentry.get_current_hub.current_scope.extra[:response_payload]).to be_blank
  end
end
```

**Expected behavior**

`expect(Sentry.get_current_hub.current_scope.extra[:response_payload]).to be_blank` will pass

**Actual behavior**

`expect(Sentry.get_current_hub.current_scope.extra[:response_payload]).to be_blank` fails

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version:
  
  sentry-rails (4.2.2)
  sentry-ruby (4.2.2)
  sentry-ruby-core (4.2.2)
  sentry-sidekiq (4.2.1)

 - Integration Versions (if any):
 
  rails (6.1.3)
  sidekiq (6.1.3)

**Comment by st0012** [comment]
@get-dmitry sorry this is actually a mistake on the document. all the `Sentry.set_*` methods add data globally. to configure data locally, you'll need to use `Sentry.with_scope` like

```ruby
Sentry.with_scope do |scope|
  scope.set_extras(debug: false)
  Sentry.capture_message("test")
end
```

**Comment by kueblc** [comment]
I also hit this in my attempt to migrate, looks like the documentation is still out of sync.

I must admit, respectfully, the migration has been a lot more troublesome than implied. Having to reimplement data scrubbing (#1140), the miscommunication about local context (this issue), and the fact that when not enabled for an environment, `Sentry` is undefined leading to `nil` exceptions whereas `Raven` handled this gracefully (I have not seen any solutions in my brief search).

All this trouble without clear benefit to the consumer, though I understand that unifying the API lowers *your* maintenance burden, it seems this one-size-fits-all approach is detrimental to your Rails users who are forced to complicate their own code base in order to keep it out of yours. I respectfully disagree with the move to make these previously available features the responsibility of the consumer. We are your paying customers after all, who may not have the resources to keep up with these changes on top of the core business responsibilities. Something to consider when doing a restructuring like this.

I digress, my question today is, how can I set the context data for an individual request in a `:before_action` for our Rails app?

With `Raven` we had a single `:before_action` on our `ApplicationController` that set up the context with User ID etc.

Can I use the above code sample and still be able to call `Sentry.capture_message` outside of the `with_scope` block? Are automatically captured exceptions going to contain the extra context as well?

**Comment by st0012** [comment]
@get-dmitry thanks again for reporting this, I've fixed the document 🙂 

> how can I set the context data for an individual request in a :before_action for our Rails app?

@kueblc  you can use `configure_scope` or `Sentry.set_*` helpers to set the data on the current scope. 

every request is wrapped inside a temporary scope, so you don't need to worry that the data will leak to other requests.

```ruby

before_action :set_context

def set_context
  Sentry.configure_scope do |scope|
    scope.set_user(id: 1)
  end

  # or

  Sentry.set_user(id: 1)
end
```

**Comment by get-dmitry** [comment]
@st0012 Thank you for clarification sand documentation fixes.

**Comment by AMHOL** [comment]
I also had to add:

```ruby
RSpec.configure do |config|
  config.around(:each, type: :controller) do |example|
    Sentry.with_scope { example.run }
  end
end
```

To stop context from leaking out of controller specs.

**Comment by st0012** [comment]
@AMHOL yeah I'm afraid that's needed for controller specs as the per-request scope is created via a middleware. it won't be necessary in request specs though.
