### ISSUE TITLE
Trouble initializing Sentry (undefined method `debug' for nil:NilClass)

### ISSUE THREAD

**Issue by brooksco** [getsentry/sentry-ruby#1386]
After updating to `sentry-rails` `4.3.3` from `4.3.1` in our Rails 6.1 app we're seeing an issue starting our Rails server. It looks like we're getting a `undefined method `debug' for nil:NilClass` error coming from the initializer for `BackgroundWorker` when it calls `configuration.logger.debug(LOGGER_PROGNAME)`.

I don't think we have an unusual logger setup to my knowledge, so I'm not sure why this is suddenly causing an issue, and I'm wondering what would have changed between these minor version releases (downgrading back to `4.3.1` fixes the issue) that we might need to account for.

<img width="738" alt="Screen Shot 2021-04-05 at 12 44 52 PM" src="https://user-images.githubusercontent.com/2280454/113600019-6c42f200-960d-11eb-9bae-a3e587e34e14.png">

**Comment by st0012** [comment]
@brooksco I think this is the same problem as https://github.com/getsentry/sentry-ruby/issues/1368, which could be solved if you move the configs into `config/initializers/sentry.rb`.

the root cause is that v4.3.3 fixes the `sentry-rails`' logger assignment, which requires the SDK to be initialized as one of the Rails initializers (this was expected but not required until now). I'll try to add a warning message to hint misplaced configurations.

**Comment by brooksco** [comment]
@st0012 ah got it, I missed that since it was closed (should have checked there first). That fixed my issue. Thanks! Maybe a warning can help the next person who comes along and does what I did.

**Comment by st0012** [comment]
@brooksco np. I hope you don’t mind I keep this open for a while for other facing the same problem 🙂

**Comment by st0012** [comment]
I've added #1387 to prevent this from happening again.
