### ISSUE TITLE
Performance monitoring of Rails app using Oj fails because of ERROR stack level too deep

### ISSUE THREAD

**Issue by lucaong** [getsentry/sentry-ruby#1389]
**Describe the bug**

Note: arguably, this is a bug with the Oj gem (that I reported [here](https://github.com/ohler55/oj/issues/651)), not with Sentry. That said, Oj is common enough in the Ruby/Rails world to be worth opening this issue, if nothing else to help other users who encounter this.

When enabling performance monitoring on a Rails app that is using the popular [Oj](https://github.com/ohler55/oj) JSON serializer, sending transactions to Sentry fails because of `ERROR - stack level too deep`.

That's because, when sending the transaction to Sentry servers, the gem attempts to `JSON.parse(JSON.generate(event))`, but the `event` contains in its data a response object, which has circular references, and Oj does not handle it well.

**To Reproduce**

  1. Create a new Rails app
  2. Add `oj` to the Gemfile
  3. Setup Oj Rails support by adding a `config/initializers/oj.rb` initializer, with the following lines (as in the Oj documentation):
```ruby
require 'oj'
Oj.optimize_rails()
```
  4. Integrate Sentry and activate performance monitoring
  5. Start the app and try performing some requests

**Expected behavior**

Performance data is sent to Sentry

**Actual behavior**

Performance data is not sent, log is filled with `ERROR - stack level too deep` messages

**Environment**
 - Ruby Version: 2.6.6
 - SDK Version: 4.3.4
 - Integration Versions (if any): Rails

## Why does the bug occur

  - `Sentry::Event` attempts to serialize/deserialize the event with `JSON.parse(JSON.generate(event))` [here](https://github.com/getsentry/sentry-ruby/blob/af68513ca4b2f7480b87ca893a81ba6cf691a8cb/sentry-ruby/lib/sentry/event.rb#L116)
  - But `Sentry::TransactionEvent` contains the whole payload of `process_action.action_controller` (see [here](https://github.com/getsentry/sentry-ruby/blob/94c28fe9a7fd1c15a10eeeb0e1c4fcac099d4166/sentry-rails/lib/sentry/rails/tracing/action_controller_subscriber.rb#L21))
  - The `process_action.action_controller` payload [contains the response object](https://github.com/rails/rails/blob/85c6823b77b60f2a3a6a25d7a1013032e8c580ef/actionpack/lib/action_controller/metal/instrumentation.rb#L35), which is an instance of `ActionDispatch::Response`
  - `ActionDispatch::Response` objects contain circular references (for example in the `@stream` and `@cv` instance variables, which contain objects that reference the response itself)
  - Oj replaces `JSON.generate` with an implementation that serializes objects by serializing their instance variables (this is _probably_ a bug, see [here](https://github.com/ohler55/oj/issues/651)), and the circular references cause the stack level too deep.

## Possible solution

Users can solve it by changing `config/initializers/oj.rb`:

```ruby
# instead of:
# Oj.optimize_rails()
# use the following:
Oj::Rails.set_encoder()
Oj::Rails.set_decoder()
Oj::Rails.optimize()
```

This still makes Rails use Oj as the JSON serializer/deserielizer, but does NOT replace `JSON.generate`, avoiding the issue.

In Sentry, a possible mitigation would be to remove the `response` object from the payload [here](https://github.com/getsentry/sentry-ruby/blob/af68513ca4b2f7480b87ca893a81ba6cf691a8cb/sentry-rails/lib/sentry/rails/tracing/action_controller_subscriber.rb#L20) (as already happens with `request` and `headers`). The `response` object is anyway not useful, as the response status is already recorded.

Feel free to close this issue, as the actual bug is in Oj, but I think being able to find this with a web search could save quite some debugging time to other users that are affected by the same issue.

Other reported issues that are probably caused by this are https://github.com/getsentry/sentry-ruby/issues/949 and https://github.com/getsentry/sentry-ruby/issues/1266.

**Comment by st0012** [comment]
@lucaong thanks for the detailed investigation 🙂 

because `JSON.generate` is probably one of the bottom-level APIs we can use to serialize objects, I don't think `sentry-ruby` can do anything here. I've subscribed https://github.com/ohler55/oj/issues/651 and will wait for `oj` maintainer's fix before taking any action for now.

**Comment by st0012** [comment]
@lucaong I just see that the `response` entry seems to be added in Rails `6.1.0` ([commit](https://github.com/rails/rails/commit/b5c6f33f0d301d8766acb5e516defe4e4eae3119)). I guess that's why not many users report the same issue. 

removing it right away may solve some users' issue. but depend on users' dependencies and application code, the SDK's breadcrumb loggers (especially `active_support_logger`) may still log payloads containing circular references. so I don't want to quickly push out patches just for removing the `response` entry.

**Comment by lucaong** [comment]
Makes sense. In any case, the bug only occurs when using `oj`, which is being fixed. The solution I posted above (omitting `Oj.optimize_rails()` and explicitly calling `Oj::Rails.set_encoder()`/`Oj::Rails.set_decoder()`/`Oj::Rails.optimize()` instead) fixes this problem also in presence of other circular references anyway.

**Comment by lucaong** [comment]
@st0012 there seems to be another possible solution that Sentry could adopt in case you don't want to wait for `Oj` to be fixed. It looks like the problem is affecting `JSON.generate` but not `JSON.dump`, so you could change the code [here](https://github.com/getsentry/sentry-ruby/blob/af68513ca4b2f7480b87ca893a81ba6cf691a8cb/sentry-ruby/lib/sentry/event.rb#L116):

```ruby
# Instead of:
JSON.parse(JSON.generate(event))

# Use JSON.dump:
JSON.parse(JSON.dump(event))
```

This should be functionally equivalent, but avoid the issue.

**Comment by laurafeier** [comment]
Just ran into this. I noticed that in my case the problem was the db connection.  Since I did not need the whole object data sent to sentry, I used this workaround:
```
  config.before_breadcrumb = lambda do |breadcrumb, hint|
    if breadcrumb.data.respond_to?(:delete)
      if (opts = breadcrumb.data.delete(:connection)&.raw_connection&.query_options).present?
        breadcrumb.data[:connection] = "#{opts[:database]}@#{opts[:host]}:#{opts[:port]}"
      end
    end

    breadcrumb
  end
``` 
This will send the connection db host & name as string instead of the whole connection object serialized as json. Maybe this helps someone.

**Comment by lucaong** [comment]
Version 3.11.4 of `oj` was just released, fixing this issue. I would still suggest replacing `JSON.generate(event)` with `JSON.dump(event)` in Sentry, as a transparent and simple change that would fix this issue also for users of earlier `oj` versions.

I will close the issue, as the original cause is fixed.

**Comment by st0012** [comment]
@lucaong thanks for reporting and tracking the issue 👍 
but I'm not going to make that change because:
1. in the standard library, `JSON.dump` is actually [built on top of `JSON.generate`](https://github.com/ruby/ruby/blob/v3_0_0/ext/json/lib/json/common.rb#L641) with some extra options we don't use right now. so, for users who don't use the `oj` gem, this change doesn't make any sense.
2. `JSON.dump` is still patched by `oj`, so switching to it doesn't make the SDK immune from `oj`'s bug in the future.

**Comment by lucaong** [comment]
Sure, it's your call 👍
