### ISSUE TITLE
Mysql2::Error: MySQL client is not connected

### ISSUE THREAD

**Issue by dhurba87** [getsentry/sentry-ruby#1422]
**Describe the bug**
Sentry is capturing breadcrumbs of delayed-job event every time, which is a long text (check the screenshot). So, capture exception repeatedly crashes the DB because of the text limit

**To Reproduce**
1. Configure sentry with `async` enabled
2. Go to console and capture the custom error message
```ruby
Sentry.capture_message("Custom error message")
```
2. Repeat the above script for a few times; Every time it records the delayed-job log in the breadcrumbs and the DB Stops working

**Environment**
 - Ruby Version: 2.7
 - SDK Version: 4.3.2
 - Integration Versions (if any): rails 6.1, delayed-job 4.1.8

This is not necessary but could be helpful.
![image](https://user-images.githubusercontent.com/7259726/116528565-b3b25a80-a8fb-11eb-9e0b-1e002180f233.png)

**Comment by st0012** [comment]
@dhurba87 are you using `sentry_logger` as breadcrumbs logger? if so, `sentry_logger` captures breadcrumbs from logging events and is likely the cause of this.
You can use `before_breadcrumb` callback to filter out/trim large breadcrumbs, like

```ruby
config.before_breadcrumb = lambda do |crumb, hint|
  crumb.message = crumb.message.byteslice(200)
  crumb
end
```

**Comment by dhurba87** [comment]
I am using `:active_support_logger` and I could replicate this issue in both `:active_support_logger` and `: sentry_logger`.

Thanks @st0012. Your script works but I needed to convert message to string `message.to_s` before calling `byteslice`.

**Comment by st0012** [comment]
So it looks like a chain reaction:
1. When a `SendEventJob` being enqueued by `async`, it generates a long sql statement.
2. The sql statement is instrumented by Rails and then captured by either one of the breadcrumb logger as a large breadcrumb.
3. The breadcrumb is stored in the current scope.
4. When an event occurs and being captured by Sentry, it now has this large breadcrumb.
5. Back to 1, and 
    - If the event payload is large enough, it would trigger the error mentioned in this issue.
    - Otherwise, this event's payload would generate an even longer sql statement.

To solve this issue, we need to break the chain. For example, using `before_breadcrumb` can make step 3 store a smaller version of breadcrumb and avoid later issues.

Some SDK-level solutions off the top of my head are:

- Ignore SDK related breadcrumb
- Give breadcrumb a size limit

I think option 1 is not realistic because breadcrumb loggers can't access that info and we need to inspect each breadcrumb's content to check that. 
Option 2 seems to be viable but I'm not sure how to set that number yet.

Will add more thoughts later.

**Comment by st0012** [comment]
@dhurba87 I can't reproduce the issue with `active_support_logger` in Rails 6 or 5.2. It looks like they only pass prepare statement sql in instrumentation. So instead of the long sql you got, I only see:

```ruby
{
connection_id: 16900, 
name: Delayed::Backend::ActiveRecord::Job Create, 
sql: INSERT INTO "delayed_jobs" ("handler", "run_at", "queue", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?), 
start_timestamp: 1622799525.903517, 
statement_name: None
}
```

I can reproduce it with `sentry_logger` though. I will add some safe guard to prevent the SDK from recording long breadcrumb messages.

**Comment by st0012** [comment]
@dhurba87 I'm releasing 4.5.1 and closing this for now. let me know if this still happen after the upgrade, then I'll reopen it 🙂
