### ISSUE TITLE
Automatically set user via sidekiq middleware

### ISSUE THREAD

**Issue by shouichi** [getsentry/sentry-ruby#1468]
**Describe the idea**

It would be nice if a sidekiq middleware transparently set `user` to the current scope so that we can track the number of affected users even for background jobs.

**Why do you think it's beneficial to most of the users**

**Possible implementation**

**Comment by st0012** [comment]
I know it'd be a convenient feature to many users, but I don't think it's something the SDK should do. 

Because it requires the SDK to "guess" what models & attributes the application uses for users and to provide to Sentry, this could be error-prone and hard to debug. 

Also, to fit different applications' use cases, the SDK will need to expose several new config options for it. For example, in my company's application the primary user model is called `Customer`, so the SDK must provide a way to configure the model name like `config.user_model_name`. Similar things are also required for attributes and scoping...etc.

Given the error-prone nature of such features + the maintenance effort, I don't plan to implement this feature yet. 

However, I think it'd be a great feature for a SDK extension though 🙂

**Comment by shouichi** [comment]
What I meant by `user` was `Sentry.get_current_scope.user` which is just a hash and application-agnostic I believe.

**Comment by st0012** [comment]
so how should the SDK get the data to set the user?

**Comment by shouichi** [comment]
In the rails app I work for we set user id to sentry in `before_action`.

```
class ApplicationController
	before_action :set_sentry_user

	def set_sentry_user
		Sentry.set_user(id: current_user.id)
	end
end
```

SDK can pick up that.

```
class ClientMiddleware
	def call(worker_class, job, queue, redis_pool)
		scope = Snetry.get_current_scope
		job["sentry_user_id"] = scope.user[:id]
		yield
	end
end

class ServerMiddleware
	def call(worker, job, queue)
		Sentry.set_user(id: job["sentry_user_id"])
		yield
	end
end
```

**Comment by st0012** [comment]
I see. I think this approach may work but I'll need to do some testing for it first 🙂

**Comment by shouichi** [comment]
I'm currently implementing this feature and would like to send a PR 😃

**Comment by st0012** [comment]
I'm looking forward to see your PR then 👍 thanks
