### ISSUE TITLE
Automatically report rails' deprecated methods usage

### ISSUE THREAD

**Issue by shouichi** [getsentry/sentry-ruby#1491]
**Describe the idea**

Report rails deprecation warnings automatically.

**Why do you think it's beneficial to most of the users**

**Possible implementation**

We can subscribe to events from deprecation warnings.

https://guides.rubyonrails.org/active_support_instrumentation.html#deprecation-rails

**Comment by st0012** [comment]
It could be a useful feature for some users. But to those who don't care about deprecation warnings much may find it annoying. So if the SDK implements it, it would be an opt-in feature and requires a new config option. Also, I think proactively reporting events that are not exceptions is out of the SDK's responsibility.

Instead of adding it into `sentry-rails` right away, a better way may be introducing another gem like `sentry-rails-deprecation`. What do you think?

**Comment by shouichi** [comment]
I agree that this feature should be opt-in. But it's nice if it's built-in to the `sentry-rails` gem because Rails deprecates methods in one version and removes them in the next version. Thus I personally want to be notified. Making it an opt-in feature and bundle it in the `sentry-rails` should be reasonable choice (I hope).

**Comment by st0012** [comment]
Once a feature is added to the SDK (opt-in or not), it's very hard to remove it and the maintenance effort stays for a long time. So I'd like to see more people request the feature before adding it. And a great way to prove its popularity is to build a gem for it first, and see how people adopt it. That's why I proposed making a gem for it first and I'd be happy to help you build the gem 🙂

**Comment by shouichi** [comment]
OK, I'll build a gem. Let's see what happens.
