### ISSUE TITLE
How can we dynamically switch between DSNs or clients?

### ISSUE THREAD

**Issue by jpcody** [getsentry/sentry-ruby#1572]
Sorry for a second ticket in a single day—evaluating switching over to Sentry, which leads to lots of questions!

Within our Rails application, we're serving both HTML and an API that powers a mobile application. We'd like to monitor the two of these as separate Sentry projects as they have different performance characteristics and demands and sometimes different teams responsible for fixes.

Previous comments about serving multiple DSNs have been solved with solutions that seem like explicitly defining multiple hubs and using them to send messages:

* https://github.com/getsentry/sentry-ruby/issues/1292#issuecomment-781035965
* https://github.com/getsentry/sentry-ruby/issues/649#issuecomment-742528958

But is it possible to switch DSNs or clients at runtime for all of Sentry's default behavior? I've been exploring doing the following in our base API controller, but it just seems to send events to nowhere:

```rb
Sentry.get_current_client.configuration.dsn = ENV["SENTRY_API_DSN"]
```

Any ideas if what we're trying to accomplish is possible?

**Comment by st0012** [comment]
Since the DSN binds at Client level, you can probably have 2 clients with different DSNs and use `Hub#bind_client` to switch the main hub's client. This way, you can have the same hub that can report to different DSNs. 

```ruby
config = Sentry::Configuration.new.tap { |c| c.dsn = DSN_2 }
client2 = Sentry::Client.new(config)

begin
  original_client = Sentry.get_current_client

  if for_api
    Sentry.get_current_hub.bind_client(client2)
  end
  
  Sentry.capture_message("send message")
ensure
  Sentry.get_current_hub.bind_client(original_client)
end
```

However, this is not the way this SDK is expected to be used and it relies on an internal API to work. So there's no guarantee that this will work and I won't spend too much time on this (it's surely an interesting scenario to think about though). I still recommend you to have multiple hubs for your use case.
