### ISSUE TITLE
sentry-sidekiq throwing ActiveJob::SerializationError in v4.7.3

### ISSUE THREAD

**Issue by earnold** [getsentry/sentry-ruby#1585]
### Issue Description

Hi there, 

Since upgrading to the latest version of `sentry-sidekiq` gem, I'm getting numerous errors like this in my logs: 

```
[ActiveJob] Failed enqueuing Sentry::SendEventJob to Sidekiq(default): ActiveJob::SerializationError (Can't serialize a Hash with reserved key "_aj_globalid")
```

Is this something I should be worried about? At a minimum, I'd like to clean it up from my logs. 

### Reproduction Steps

Use rails & active job & sidekiq & sentry. 

### Expected Behavior

There shouldn't be errors with normal usage. 

### Actual Behavior

Lots of errors in my logs. 

### Ruby Version

3.0.2

### SDK Version

sentry-sidekiq (4.7.3)

### Integration and Its Version

Rails/Sidekiq

### Sentry Config

```Ruby
Sentry.init do |config|
  config.dsn = ENV["SENTRY_DSN"]

  config.breadcrumbs_logger = [:active_support_logger, :http_logger]

  # Set tracesSampleRate to 1.0 to capture 100%
  # of transactions for performance monitoring.
  # We recommend adjusting this value in production
  config.traces_sample_rate = 0.1

  config.async = lambda do |event, hint|
    Sentry::SendEventJob.perform_later(event, hint)
  end

  config.backtrace_cleanup_callback = lambda do |backtrace|
    Rails.backtrace_cleaner.clean(backtrace)
  end

  config.breadcrumbs_logger = [:active_support_logger, :http_logger]

  config.environment = Rails.env

  # this uses Rails' parameter filter to sanitize the event payload
  filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  config.before_send = lambda do |event, _hint|
    filter.filter(event.to_hash)
  end
end
```

**Comment by st0012** [comment]
@earnold I'm not sure what could cause this because `sentry-sidekiq` should already filter the `_aj_globalid` key:

https://github.com/getsentry/sentry-ruby/blob/53deb6eeefef79a06a89660d7a4fb073e53c61e5/sentry-sidekiq/lib/sentry/sidekiq/error_handler.rb#L9

can you provide an example app that can reproduce the problem? it'll help me debug this issue.

an unrelated note: we don't recommend using the `async` option anymore and I suggest you to remove it because it could more harm than good to your app. you can find the full explanation here: https://github.com/getsentry/sentry-ruby/issues/1522
