### ISSUE TITLE
Support the new Rails standard error reporting interface

### ISSUE THREAD

**Issue by georgeclaghorn** [getsentry/sentry-ruby#1630]
Rails 7.0 will add a standard interface for reporting errors to error tracking services like Sentry (rails/rails#43625).

```ruby
# Report any error raised and continue execution:
Rails.error.handle do
  # ...
end

# Report and re-raise any error:
Rails.error.record do
  # ...
end

# Report an error directly:
Rails.error.report(error)
```

Additionally, Rails’s internal execution wrappers have been updated to report errors via `Rails.error.report`.

The Sentry SDK can opt in to the new interface via [`Rails.error.subscribe(subscriber)`](https://github.com/rails/rails/blob/89b1cc4818e3cb08ed403441001b8853502a637c/activesupport/lib/active_support/error_reporter.rb#L63-L67), where `subscriber` is an object implementing a `report` method. `report` takes a positional exception argument and `handled:` and `context:` keyword arguments.

```
report(Exception, handled: Boolean, context: Hash)
```

Supporting the new interface will allow Sentry users to use the standard `Rails.error.{handle,record,report}` methods. And in the future, when the standard interface is more widely deployed, it’ll make it easier for Rails users to try and adopt Sentry.

**Comment by st0012** [comment]
Yeah I'm aware of this new interface, I also participated the initial discussion. But it won't work along with the current middlewares SDK injects because it'll cause double reporting (middleware report and re-raise the issue, which'll be reported again by the reporter). 

So to make this work without maintaining 2 exception capturing approaches, we need to replace the current middleware approach with
- `ActionDispatch::Executor`'s callbacks to start Sentry transaction & scope
- Rails' exception interceptor (https://github.com/rails/rails/pull/23868) to report exceptions. 
   - This only works with Rails 6+, which means we need to drop Rails 5 support.

The overall plan would look like this:

1. Drop Rails 5 support & Implement the above changes (v4.9.0?)
2. Check if `ActiveJob` integration would face a similar issue too.
3. Add support for the new error report interface (v4.10.0?)

WDYT?

**Comment by st0012** [comment]
> ActionDispatch::Executor's callbacks to start Sentry transaction & scope

After digging a big deeper, I found that the callback isn't the best place for doing that. Because the callback is not registered directly on the middleware but on a `ActiveSupport::Executor` instance, which can't access the request data. 

And while `ActionDispatch::Callbacks` has access to the request, it's registered after `ActionDispatch::DebugExceptions`. This means the scope will end before the exceptions are captured by the interceptors, thus those exception events won't contain any scope data.

**Comment by st0012** [comment]
I finally got time to work on this and it looks like the `ErrorReporter` isn't automatically plugged in into things like the interceptor at the moment so there's no double reporting concern. This means that supporting this will be straight-forward and should be included in the next minor release 🙂
