### ISSUE TITLE
AR arguments in ActiveJob shows address not id

### ISSUE THREAD

**Issue by mfazekas** [getsentry/sentry-ruby#1645]
### Issue Description

ActiveRecord arguments in ActiveJob aren't really usefull:

```sh
[
#<PackageQuote:0x00007fad7331ff60>
]
```

### Reproduction Steps

In a rails app invoke a job with an ActiveRecord object as one of the arguments, which reports an error to sentry. The arguments hash will contain the address of the record instead of the id

### Expected Behavior

AR records passed as arguments to jobs should be dumped with for example class and id, not address.

### Actual Behavior

Arguments are serialised with addresses instead
```sh
[
#<PackageQuote:0x00007fad7331ff60>
]
```

### Ruby Version

2.7.4

### SDK Version

4.8.1

### Integration and Its Version

Rails

**Comment by st0012** [comment]
Thanks for reporting this. I understand that the current format isn't super helpful and that's because we serialize the entire payload with `JSON.generate`, which uses `#to_s` underneath.

To do what you proposed, we need to walk through the arguments (which can be a nested structure) and serialize different objects in different ways. This is what we want to avoid because it's easy to cause issues and/or impact performance for some users.

So instead of change the serialization method for every user, I'll think about some customization approaches that we can provide to users.

Also, given that this is not a regression nor does it break anything, I don't think it's a bug but a lack of support. So I'm converting this issue to a feature proposal.

**Comment by mfazekas** [comment]
> So instead of change the serialization method for every user, I'll think about some customization approaches that we can provide to users.

I think it's rails, we know users pass AR objects to the jobs, and we know the current serialisation is not usefull for that case. IMO the default serialisation should support that. Why would anyone want to see this as ar job argument: ```[#<PackageQuote:0x00007fad7331ff60>]```

**Comment by st0012** [comment]
I'm already preparing a PR for this. And since it's duplicated with #1643, I'm closing this and will move the discussion there.
