### ISSUE TITLE
Don't cause `NoMethodError` when calling `Sentry.*` with an uninitialized SDK

### ISSUE THREAD

**Issue by st0012** [getsentry/sentry-ruby#1706]
It should be either no-op or raising an exception, as the SDK should always be initialized (this is a requirement across all Sentry SDKs).

I prefer raising exceptions for such condition and have proposed it in a recent discord discussion as well. But we also have methods like `Sentry.capture_*` that current does nothing instead of raising an exception. So my concerns are:

- If I make methods like `Sentry.set_tags` raise exceptions, should I also change `Sentry.capture_*`'s behaviors.
- If the answer is `yes`, should we consider that as a breaking change?

As maintainers we can argue that it's a bug fix so it's not a breaking change (can go out at any patch). But to some (probably few) users, it'll be a change that break their app without actually providing visible benefits to them (should be in a major release).

So I think the first step would be to stop causing the `NoMethodError`. And then we can discuss when to start raising the exception.

**Comment by sl0thentr0py** [comment]
@st0012 so python no-ops on `capture_*` stuff without an init. `set_tag` still works since the hub has a scope attached (but no client). I think we prefer no-ops because the first priority is to _never_ break user apps due to whatever reason. If they make an init mistake and don't see events, that can be resolved subsequently but at least it doesn't break their production unexpectedly by throwing an exception.

**Comment by st0012** [comment]
@sl0thentr0py In `sentry-ruby`, there will be no hub and no scopes if the SDK is not initialized. So methods like `set_tags` won't work. How does `sentry-python` create hub and scopes when it's not initialized? Is it done upon import?

Anyway, I'm fine with the no-op approach since it aligns with other SDKs. Will open a PR shortly.
