### ISSUE TITLE
Active Storage transactions are incorrectly named

### ISSUE THREAD

**Issue by lewispb** [getsentry/sentry-ruby#1739]
### Issue Description

I'd expect Active Storage transactions / spans to be named with the Controller#action format that other Rails requests use.

### Reproduction Steps

App I created to reproduce: https://github.com/lewispb/sentry-as-issue-repro

Or:

1. rails new appname
1. rails active_storage:install
1. rails g scaffold post title:string cover:attachment
1. Install Sentry Rails with tracing

And then:

1. Upload a cover to the post
1. View the transaction in Sentry Performance

### Expected Behavior

Transaction name is "ActiveStorage::Representations::RedirectController#show"

### Actual Behavior

Transaction name is "/rails/active_storage/blobs/redirect/longid"

Transactions are not grouped.

<img width="936" alt="Screenshot 2022-02-20 at 19 29 15" src="https://user-images.githubusercontent.com/1773614/154860769-5624bea8-3968-4c5e-a3b7-1fba1a9086c0.png">

### Ruby Version

3.0.3

### SDK Version

5.1.0

### Integration and Its Version

Rails

### Sentry Config

https://github.com/lewispb/sentry-as-issue-repro/blob/main/config/initializers/sentry.rb

**Comment by st0012** [comment]
Wow this issue is way more complicated to debug than I thought. 

Some context:

1. The SDK first sets the scope's transaction name in `Sentry::Rack::CaptureExceptions` with request route.
2. If the request enters a controller action, [this callback](https://github.com/getsentry/sentry-ruby/blob/master/sentry-rails/lib/sentry/rails/controller_transaction.rb) sets it with a nicer format.

And since AS assets are rendered by controller actions, those requests should have the transaction name set by 2).

**BUT**, because [ActiveStorage streams controller actions](https://github.com/rails/rails/blob/7-0-stable/activestorage/app/controllers/active_storage/base_controller.rb#L5), the subsequent operations will be handled in another thread. And those original requests actually never enter 2) and thus never have the correct transaction name set.

And since the streaming support has been removed in https://github.com/rails/rails/pull/44244, which [may be backported to 7.0](https://github.com/rails/rails/issues/44321#issuecomment-1045456817) (I've tested that the problem doesn't occur with Rails master), I think we can call it a Rails bug and has been fixed?

**Comment by lewispb** [comment]
Great investigation @st0012! Thank you!

> I think we can call it a Rails bug and has been fixed?

Agreed.
