### ISSUE TITLE
exception happened in background worker: ActiveRecord::ConnectionNotEstablished

### ISSUE THREAD

**Issue by sdogruyol** [getsentry/sentry-ruby#1745]
### Issue Description

This started to happen after we upgraded our application from Rails 6.1 to Rails 7.0.2.2.

Sentry SDK just crashes in the middle of the request with an unrelated stacktrace and the following error

```
ERROR -- sentry: exception happened in background worker: ActiveRecord::ConnectionNotEstablished
```

The weird part is that our application uses *Sequel* and not ActiveRecord.

### Reproduction Steps

Not available

### Expected Behavior

Should not crash the request

### Actual Behavior

Crashes the request with 500 error

### Ruby Version

3.0.3

### SDK Version

5.0.2

### Integration and Its Version

5.0.2

### Sentry Config

```ruby
# frozen_string_literal: true

Sentry.init do |config|
  config.dsn = ENV.fetch('SENTRY_RAVEN_KEY')
  config.send_default_pii = true
end
```

**Comment by st0012** [comment]
@sdogruyol Thanks for reporting the issue. 

The root cause is that we have [this code](https://github.com/getsentry/sentry-ruby/blob/master/sentry-rails/lib/sentry/rails/background_worker.rb) in the SDK's background worker to make sure we release `ActiveRecord`'s connection if it acquired one. The code was written assuming the client would use `ActiveRecord`, which is not the case for you (and perhaps some other users).

So in #1746, I tried to replace the code with a higher-level helper. But because I don't know how you set up Sequal with your Rails app, I can't test it for you. Can you try the branch and let me know if it fixes the issue?

**Comment by sdogruyol** [comment]
Hey @st0012 thanks a lot for the response.

I just tried your branch and it doesn't seem to fix the problem. Still getting the same `exception happened in background worker: ActiveRecord::ConnectionNotEstablished` exception.

**Comment by st0012** [comment]
@sdogruyol can you set `config.debug = true` in your initializer and provide me the error output? (which should include backtrace)

**Comment by ajparise** [comment]
> The weird part is that our application uses Sequel and not ActiveRecord.

I am experiencing this issue after upgrading sentry-rails from 4.2.2 to 5.1.0.
The app is running Rails 5.2.6.2, it uses Mongoid and AR, but it does not have a persistent or default AR connection setup.

As a workaround I've resorted to synchronous event sending.

```ruby
config.background_worker_threads = 0
```

**Comment by st0012** [comment]
@sdogruyol @ajparise sorry for the delay. I've added https://github.com/getsentry/sentry-ruby/pull/1769 to address the issue, which I think should solve the problem. it'd be great if you can help me verify the fix, thx 🙂

**Comment by ajparise** [comment]
@st0012 verified, thanks for the fix.

**Comment by st0012** [comment]
@ajparise thank you 👍
