### ISSUE TITLE
sentry-ruby gem seems to be missing lib directory entirely

### ISSUE THREAD

**Issue by pravi** [getsentry/sentry-ruby#1815]
### Issue Description

sentry-ruby gem only includes these two files
LICENSE.txt  README.md

### Reproduction Steps

```
(debian-sid)pravi@mahishi:/tmp$ sudo gem install sentry-ruby
[sudo] password for pravi: 
Fetching sentry-ruby-5.3.0.gem
Fetching sentry-ruby-core-5.3.0.gem
Fetching concurrent-ruby-1.1.10.gem
Successfully installed concurrent-ruby-1.1.10
Successfully installed sentry-ruby-core-5.3.0
Successfully installed sentry-ruby-5.3.0
Parsing documentation for concurrent-ruby-1.1.10
Installing ri documentation for concurrent-ruby-1.1.10
Parsing documentation for sentry-ruby-core-5.3.0
Installing ri documentation for sentry-ruby-core-5.3.0
Parsing documentation for sentry-ruby-5.3.0
Installing ri documentation for sentry-ruby-5.3.0
Done installing documentation for concurrent-ruby, sentry-ruby-core, sentry-ruby after 4 seconds
3 gems installed
```

```
(debian-sid)pravi@mahishi:/tmp$ ls /var/lib/gems/3.0.0/gems/sentry-ruby-5.3.0/
LICENSE.txt  README.md

```

Though I can see sentry-ruby-core including gemspec for both gems. Is this expected behavior? It is very confusing though.

### Expected Behavior

It should match the files in
https://github.com/getsentry/sentry-ruby/tree/master/sentry-ruby

### Actual Behavior

It includes only LICENSE.txt  README.md

### Ruby Version

2.7

### SDK Version

5.3.0

**Comment by st0012** [comment]
Since this behavior doesn't affect how you should use the SDK, I think it's not a bug.

We introduced `sentry-ruby-core` to work around `faraday` dependencies issue in the past, that is:

- `sentry-ruby-core`: where the SDK actually live, without hard version requirement on `faraday`
- `sentry-ruby`: depend on `sentry-ruby-core` + hard version requirements on `faraday`
- `sentry-*`: depend on `sentry-ruby-core`

But now `faraday` is no longer a dependency, maybe we can simplify the structure by deprecating the role of `sentry-ruby-core`? 

- `sentry-ruby`: where the SDK actually live
- `sentry-ruby-core`: depend on `sentry-ruby`
- `sentry-*`: depend on `sentry-ruby`

Wdyt? @sl0thentr0py
