### ISSUE TITLE
ERROR -- sentry: "exception happened in background worker: execution expired

### ISSUE THREAD

**Issue by gerardo-navarro** [getsentry/sentry-ruby#1878]
On a production instance, we receive this error message. We have looked into this issue, but we where not able to find the cause for this error until now. We hope that the community has an idea.

## Actual Behavior

This error message is logged. The users are not impacted.

The error message suggests that a background worker is involved. This is unexpected as the instance logging this message is a rails (puma) server. The background worker is deployed on another instance and is not logging any sentry-related error messages. 

-------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                      message                                                      |
|---------------|-------------------------------------------------------------------------------------------------------------------|
| 1661697946874 | E, [2022-08-28T14:45:46.874085 #12] ERROR -- sentry: "exception happened in background worker: execution expired" |
-------------------------------------------------------------------------------------------------------------------------------------

## Ruby Version
`Ruby 3.0.3`

## Sentry SDK
`5.3.1`

## Integration and Its Version
- `Rails '~> 6.1.3'`
- `Ruby 3.0.3`
- `delayed_job (4.1.9)`

## Sentry Config

```ruby
# frozen_string_literal: true

Sentry.init do |config|
  config.breadcrumbs_logger = %i[
    active_support_logger
    http_logger
  ]
  config.dsn = Rails.application.credentials.dig(:sentry, :dsn)
  config.environment = Rails.application.credentials.dig(:sentry, :environment)
  config.release = ENV['SENTRY_RELEASE_ID']

  config.traces_sample_rate = 0.0
end
```

**Comment by st0012** [comment]
Let me clarify the message a bit: the "background worker" here is the SDK's background worker, which is initialized by default for every Ruby process that runs the SDK. So even in Puma webserver's process, there's a SDK's background worker too. It's not your `delayed_job` background worker.

And the SDK initializes background workers because we want to dispatch user's Sentry events asynchronously but also without using user's worker resource (see https://github.com/getsentry/sentry-ruby/issues/1522 for more info). 

As for the `execution expired` error, it's likely because of the SDK sending `Net::HTTP` requests (through the background worker) but failed due to some network issues it encountered.
