### ISSUE TITLE
Throw warning when release is not a string

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-ruby#2004]
avoid issues like https://github.com/getsentry/sentry-ruby/pull/2000

**Comment by lysenkooo** [comment]
Since it's completely brake an app I suggest to throw exception during initialize, not warning. Otherwise you're going end up with exceptions during app run and that's difficult to debug since it's flaky and failing in https://github.com/getsentry/sentry-ruby/pull/2000/files#diff-7fc5d9f44c02895e190c382e5ba78d18b3c7d44d36bde96639dd7608b7492f0eL77

**Comment by st0012** [comment]
Since we're already validating some config options (mostly procs) with `ArgumentError`, I think it's fine to do the same for `config.release` too. The exception could either be `ArgumentError` or `TypeError`.
