### ISSUE TITLE
Naming Conventions for Propagating Traces

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-ruby#2200]
**Describe the idea**
We have controls in SDKs to influence to what endpoints tracing headers should be propagated. This allows users to control what is being traced, where data is being sent. This is because not all endpoints are functionally relevant for users to trace (3rd parties) and sometimes they just don't want to have distributed tracing.

Today ruby has this option documented, [config.propagate_traces](https://docs.sentry.io/platforms/ruby/guides/rails/configuration/options/?original_referrer=https%3A%2F%2Fwww.google.com%2F#:~:text=max_breadcrumbs%20%3D%2030-,propagate_traces,-By%20default%2C%20Sentry). While in JS for example there is [tracePropagationTarget](https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/#tracepropagationtargets)

These play a similar role but do different things, boolean vs array of regexes, ruby BE and JS FE. Should we have the same naming convention in Ruby as others?

**Why do you think it's beneficial to most of the users**
This is really just a naming convention thing, to have it same or similar across SDKs

**Possible implementation**

Python has [trace_propagation_targets](https://docs.sentry.io/platforms/python/configuration/options/?#trace-propagation-targets) as optional, and is probably a better model for how Ruby should behave.

**Comment by natikgadzhi** [comment]
Let me see if I understand this correctly:

- When we add `config.trace_propagation_targets` instead of `config.propagate_traces`, the behavior is going to change: If propagation was set to true, then the equivalent value for `traca_propagate_targets` would be something like `'.*'`.
- We could either just change the option and ship the change with a one-time release. The old config value will be ignored, the new one will be effective. Folks who have `config.propagate_traces = true` and who would upgrade without reading the changelog would be _quite surprised_.
- Or, we can add the new value and still support the old value. If `config.propagate_traces = true`, we can just set `config.trace_propagate_targets += '.*'` to propagate to all targets, AND we can emit a deprecation warning. 

It looks like we should add the new option, and soft-deprecate the old one. 

Another gotcha: we should prepare and ship the documentation change at the same time.

How far off am I? If my understanding is more or less alright, I'm happy to put this together. /cc @sl0thentr0py

**Comment by sl0thentr0py** [comment]
I added missing docs 
https://github.com/getsentry/sentry-docs/pull/8813
closing this
