### ISSUE TITLE
Massive increase in transactions upgrading from 5.13.0 to 5.17.3

### ISSUE THREAD

**Issue by rnystrom** [getsentry/sentry-ruby#2318]
We did some routine upgrades on 5/24:

![CleanShot 2024-06-04 at 16 34 03@2x](https://github.com/getsentry/sentry-ruby/assets/739696/b08807d6-e9ce-4130-8207-09359975f2ff)

This was later on a Friday. When our weekday traffic picked up next week, we noticed an alarming number of transactions being logged:

![CleanShot 2024-06-04 at 16 31 56@2x](https://github.com/getsentry/sentry-ruby/assets/739696/b77acd35-c2ec-4f72-9da6-bdaa47fd1fc5)

This resulted in a much larger Sentry bill than we were expecting. We've been trying to trace where this came from, but we can't find anything. All the increase in transactions are coming from our API service (rails).

Our frontend is NextJS, and we also upgraded those Sentry dependencies from 7.110.1 to 8.4.0. I mention that because of our tracing setup. If the client were to send many more requests with tracing enabled, I guess that could result in a large increase in transactions.

```rb
# frozen_string_literal: true

Sentry.init do |config|
  config.dsn = Rails.application.credentials&.sentry&.fetch(:dsn)
  config.breadcrumbs_logger = [:active_support_logger, :http_logger, :sentry_logger]
  config.enabled_environments = ["production"]
  config.release = ENV["RELEASE_SHA"]

  if Sidekiq.server?
    config.excluded_exceptions.delete("ActiveRecord::RecordNotFound")
  end

  config.traces_sampler = lambda do |sampling_context|
    unless sampling_context[:parent_sampled].nil?
      next sampling_context[:parent_sampled]
    end

    transaction = sampling_context[:transaction_context]
    op = transaction[:op]

    if op.match?("sidekiq")
      0.000000000001
    else
      0.0
    end
  end
end
```

However I do see our client sample rate still at 2.5% when looking at traces. Example:

![CleanShot 2024-06-04 at 16 38 32@2x](https://github.com/getsentry/sentry-ruby/assets/739696/8cb7d634-66fc-4910-9885-6653b5009432)

We're having a hard time understanding where the increase in transactions is coming from. I've looked at the releases between 5.13 and 5.17 and don't see anything obvious.

I'd love some help to understand what is happening. Either some explanation on what new transactions are being sent, where to look in Sentry to see more details, or anything else.

Thank you!

**Comment by sl0thentr0py** [comment]
@rnystrom the only thing that changed on the ruby side during those releases for transactions is more `DelayedJob` tracing but you don't seem to be using that. 

Your frontend upgrade to v8 also includes our massive OpenTelemetry refactor so that could indeed cause more frontend (and thus mode linked backend) transactions. 

I need more info to help you further:

* your sentry org slug (if you don't want it visible publicly on github, please route your request through support@sentry.io and link this issue)
* what kind of transactions have increased in volume compared to before
* your frontend Sentry initializer config

**Comment by sl0thentr0py** [comment]
thx @rnystrom, don't know the exact problem yet but some observations

### Trace differences before / after

if I look at the `/[org]/inbox/[inboxView]` transaction before May 25, I see a much smaller trace.

<img width="961" alt="image" src="https://github.com/getsentry/sentry-ruby/assets/6536764/5e90b8f0-27c4-4903-93ef-5478af6ab566">

compare that to a more recent trace which has 177 events in the compared to the 21 above.

<img width="1274" alt="image" src="https://github.com/getsentry/sentry-ruby/assets/6536764/8ae04c9e-928f-484d-8777-94acc3f9f23e">

So for some reason, the traces started on your frontend now are getting linked to far more Rails transactions (via the `sentry-trace` and `baggage` headers). The frontend seems to be keeping the same `trace_id` alive for very long.

Because you're using the `parent_sampled` to decide your rails sampling in your `traces_sampled`(as you should), you will always respect the frontend's sampling decision on the Rails side and thus you have far more transactions getting sampled via that frontend sampled trace.

### Further steps

* I'm not 100% certain but I don't see any change on the ruby/rails side that would've caused the increase
* The JS SDK changed a lot in how it does tracing with v8 because it now uses OpenTelemetry under the hood, so I will ask our frontend folks to take a look at this too
  * If you want to verify this, you could downgrade the NextJS Sentry SDK back to 7.112.2

**Comment by sl0thentr0py** [comment]
for cross reference, here's a running tracker of problems with NextJS in v8

https://github.com/getsentry/sentry-javascript/issues/11046

**Comment by sl0thentr0py** [comment]
ok @Lms24 helped me figure out what's up.

v8 changed how long traces live here
https://github.com/getsentry/sentry-javascript/issues/11599

So if your application has a page that lives for very long without navigation, your traces will stay alive for much longer with v8. This is valuable feedback on the change, so we might make it more visible or add some tweaks/config to not let traces get too big.

For now, if you're not happy with this change, you can either
* just sample less if you want to use less quota (the traces are accurate, they just are much longer now) 
* you could do the following reset of the active trace in some kind of lifecycle hook (not navigation) which you think should be your trace boundary (this is sort of subjective to the type of application)

```js
Sentry.getCurrentScope().setPropagationContext({
    traceId: uuid4(),
    spanId: uuid4().substring(16),
})

**Comment by rnystrom** [comment]
Ahh ok sounds good. I'll start by lowering the client sample significantly to start. The change makes sense, it was just quite shocking the impact it had on us (particularly our bill...). I'll report back once we deploy the change.

**Comment by rnystrom** [comment]
So if I lower the client sample rate to, say, `0.0025` from `0.025` (10x lower), we will have far fewer API traces, but now we will also have much less client traces. This is a bummer as now we'll have significantly less client trace data for perf monitoring + debugging just to keep our API spend lower.

We may need to implement a custom trace boundary like you suggested, though this entire change is just quite a headache as it changes the trace sampling mental model.

**Comment by rnystrom** [comment]
No worries appreciate the understanding. We definitely want to stay up to date with SDKs so we can tag along with improvements and new features.

If you all have any advice on our sampling setup so that we can receive more client-side sampling without blowing up our quotas with API sampling, that'd be very helpful.

**Comment by sl0thentr0py** [comment]
> If you all have any advice on our sampling setup so that we can receive more client-side sampling without blowing up our quotas with API sampling, that'd be very helpful.

You could in principle ignore `parent_sampled` (the client's sampling decision) sometimes and reduce the API sampling rates independently for API routes you don't care about but that just means those API transactions will be missing from the complete frontend-backend trace.
