### ISSUE TITLE
Ruby Stack Trace Missing Gem Folder Names in Sentry Reported Paths

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry-ruby#2407]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A user is reporting that Sentry is modifying Ruby stack traces by stripping out the gem folder names, making it difficult to trace errors back to their source. Specifically, when Sentry displays paths like active_record/connection_adapters/abstract_mysql_adapter.rb, it omits the gem folder name, which should be something like activerecord-5.2.4.1/. The user needs the full gem path preserved to navigate the stack trace in their IDE and identify the correct gem, as internal paths within gems can be ambiguous without the versioned folder name.

### Expected Result

The stack trace paths should include the full gem folder names (e.g., activerecord-5.2.4.1/) so that users can easily navigate them within their IDEs.

### Actual Result

Sentry is stripping the gem folder names from the paths, leaving only the internal paths within the gem (e.g., active_record/connection_adapters/abstract_mysql_adapter.rb). This makes it difficult to map these paths to the real gem files on the system.

### Product Area

Processing

**Comment by sl0thentr0py** [comment]
Okay, so this is the default behavior that comes from our default[`BacktraceCleaner`](https://github.com/getsentry/sentry-ruby/blob/master/sentry-rails/lib/sentry/rails/backtrace_cleaner.rb) which currently does the following transformation.
```ruby
(byebug) ruby_lines.last
"/Users/neel/.rvm/gems/ruby-3.0.0/gems/puma-6.4.0/lib/puma/thread_pool.rb:155:in `block in spawn_thread'"
(byebug) backtrace_cleanup_callback.call(ruby_lines).last
"puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'"
```

Note that the version of the gem is included in the transformed line but the path is shortened. This has been the default behavior for a while so I will not classify this as a bug. This is intentional because it reduces payload size and final UX noise/clutter.

This particular gem line transformation comes from `ActiveSupport::BacktraceCleaner` here.
https://github.com/rails/rails/blob/dfd1e951aa1aeef06c39fffb2994db8a8fa1914f/activesupport/lib/active_support/backtrace_cleaner.rb#L118-L125

If you really do not want this behavior, you can do the following which will avoid all of our backtrace cleanup.
```ruby
  config.backtrace_cleanup_callback = lambda { |x| x }
```

That couple with the product side `abs_path` switch that @alxwrk mentioned above should get you what you want.

**Comment by bughit** [comment]
@sl0thentr0py

> config.backtrace_cleanup_callback = lambda { |x| x }

Furthermore, I expect that this wouldn't work even in current Rails. It will prevent your BacktraceCleaner from mangling the paths, but `compute_filename` will still strip the `longest_load_path` prefix.

Since no workaround is currently available, this should not be classified as a "questions". This is a problem and it requires a solution.

**Comment by sl0thentr0py** [comment]
> This is incorrect, at least for rails 5.2.

Ok fair, I tested with a newer rails.

> this should not be classified as a "question".

Please don't pay that close attention to what we classify the issue as, that is just internal backlog management for us and I will classify it in a way that makes sense to us.

I am trying to help you fix your problem but we also have other constraints that are not just about solving your particular problem. For instance, I cannot release a change to the stacktrace payloads without a major version release of the SDK since they will break [Issue Grouping](https://docs.sentry.io/product/issues/grouping-and-fingerprints/) for other existing users.

Coming back to your exact problem:

1. The product side should make it possible to view `abs_path` in the UX and I believe they will do so shortly when time permits.
2. I will add a new boolean configuration attribute called `strip_backtrace_lines` (default true) that will control that `compute_filename/longest_load_path` flow and you can thus disable all of it.

That work?
