### ISSUE TITLE
Introduce a way to easily add a Fingerprint to exceptions like Raven.extra_context

### ISSUE THREAD

**Issue by parreirat** [getsentry/sentry-ruby#884]
Use case:

Am re-raising some exceptions, or explicitly raising ones, while calling 

```
Raven.extra_context
Raven.tags_context
Raven.user_context
```

Have searched around and found that you can pass a fingerprint to explicitly segregate groups of exceptions on Sentry, which would be amazing to have in a use case we have.
However I could not find any way to do this through anything except `capture_message` or `capture_exception`.

Can this be added in like a `Raven.fingerprint_context` or similar as well?
If not, how can I currently do this?

Thanks!

**Comment by pedrofurtado** [comment]
any news? :+1:

**Comment by st0012** [comment]
since the old `sentry-raven` gem has entered maintenance mode, we won't add this method to it. 

however, if you have upgraded to the new SDK, you can do something like this:

```ruby

Sentry.configure_scope do |scope|
  scope.set_fingerprint(your_fingerprint)
end # configure fingerprint globally

Sentry.capture_exception(exception)

# or 

Sentry.with_scope do |scope|
  scope.set_fingerprint(your_fingerprint) 
  Sentry.capture_exception(exception) # only applies to events sent in the block
end
```

(if you haven't migrated to the new SDK, here's the [migration guide](https://docs.sentry.io/platforms/ruby/migration/) that will help you do that 🙂 )

I hope this comment answers your question. I'm closing this now, but feel free to open another issue if the above sample doesn't work.
