### ISSUE TITLE
Different configuration for integrations (Sidekiq)

### ISSUE THREAD

**Issue by marcsasson** [getsentry/sentry-ruby#893]
I would like to have a different configuration for integrations.
My use case is for Sidekiq. I would like for Sidekiq errors of type 'ActiveRecord::RecordNotFound' (which is ignored by default) to be sent but not in other workflows.
Is this currently possible?

**Comment by st0012** [comment]
Currently, we don't support customizing exception types for different integrations. I can understand the use case for this, but in order to support we probably need something like cascading configurations:

```ruby
config.excluded_exceptions = [#...]
config.sidekiq.excluded_exceptions = excluded_exceptions - ActiveRecord::RecordNotFound
```

I will put this on my todo list, but at we be able to won't support it in the next major release.

**Comment by aert** [comment]
I just got bitten by this exception not being reported in Sidekiq.
Maybe let's update the docs to signal that by 4xx we also mean `ActiveRecord::RecordNotFound` ?

**Comment by st0012** [comment]
@aert where do you want to put it though?

**Comment by bdewater** [comment]
You could try [`$0`](https://ruby-doc.org/3.3.6/globals_rdoc.html#label-Processes) to match against the process name. We're using GoodJob with `bin/good_job` so we can do this:
```rb
if $0["good_job"]
  config.excluded_exceptions -= ["ActiveRecord::RecordNotFound"]
end
```
