### ISSUE TITLE
capture_message not producing entry on app

### ISSUE THREAD

**Issue by aaron-humerickhouse** [getsentry/sentry-ruby#953]
I'm trying to create a rake task that will log to Sentry as a quick connection task and the message will not log to Sentry app.

```
namespace :observability do
  task :sentry_test => :environment do
    event = Raven.capture_message(
      "Testing Sentry from a rake task for environment '#{ENV['SENTRY_ENVIRONMENT']}'",
      level: :info
    )

    puts "Sent message to Sentry. Event id: #{event.event_id}"
  end
end
```

When the rake task exits, I get the event id like I expect.  However when I navigate to the Sentry App and look for that event, it doesn't appear.  I've checked back several minutes later and it's not there.  

I'm in Rails context and have the DSN set as well as the environment.  In `Raven.configuration` I see `@scheme`, `@public_key`, `@host`, and `@project_id` are being set.  These instance variables make up my DSN. If I run `rails c` and execute `Raven.capture_message` the message appears appropriately.

**Comment by dzello** [comment]
I'm getting the same thing after upgrading to the 3.0.0 version. I get a `Raven::Error - the server responded with status 400` in my logs when I try to send any errors.

**Comment by st0012** [comment]
can you provide more information about your app? like what's the Rails version and Ruby version. it'd be even better if you can provide a sample app that can reproduce this issue.
I'm asking because I added the exact same task to our [Rails 6 example](https://github.com/getsentry/raven-ruby/tree/master/examples/rails-6.0) and it worked without any issue.
